
server:
  port: 8007 # 服务端口

spring:
  devtools:
    restart:
        enabled: true  #设置开启热部署
  application:
    name: guli-edu-teacher # 服务名
  profiles:
    active: dev # 环境设置：dev、test、prod
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.1:3306/guli_edu?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus: #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.guli.edu.entity
  mapper-locations: classpath:xml/*.xml
#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8004/eureka/
#eureka服务器上获取的是服务器的ip地址，否则是主机名
  instance:
    prefer-ip-address: true

